# -*- coding: utf-8 -*-
"""Production showcase photos — the single source for /production-showcase/
and the homepage "What We Build" section.

Each photo lives in assets/img/showcase/<file>.webp with a <file>-640.webp
variant. To add a photo: drop both files there, add an entry below, then run
`python3 tools/production_showcase_build.py`.

Geography is only named where it is known (venue or campaign shows it);
otherwise the alt text says Türkiye. Alt text describes what is visible.
"""

# (anchor, title, short line for the homepage card, intro for the gallery page)
CATEGORIES = [
    ("led-tunnels", "LED Tunnels &amp; Entrance Arches",
     "Walk-through LED tunnels and lit arches that open the show.",
     "Walk-through LED tunnels, illuminated arches and light corridors that set the tone before guests reach the room."),
    ("stages", "Stages, LED Walls &amp; Show Lighting",
     "LED walls, truss and moving-light rigs, indoors or open-air.",
     "Main stages built around LED walls, truss and moving-light rigs, for plenaries, award nights, open-air ceremonies and live performance."),
    ("conference", "Conference &amp; Plenary Set-ups",
     "Plenary rooms for hundreds, with stage, screens and branding.",
     "Classroom and theatre-style plenary rooms for dealer meetings, management summits and congresses, with stage, screens and in-room branding."),
    ("registration", "Registration &amp; Welcome Desks",
     "LED-fronted counters and full accreditation lines.",
     "Branded registration counters, LED-fronted welcome desks and accreditation lines for smooth, on-brand arrivals."),
    ("branded-entrances", "Branded Entrances &amp; Building Wraps",
     "Entrances, façades and gates dressed in your campaign.",
     "Hotel entrances, building façades, gates and outdoor flags dressed in the event campaign."),
    ("3d-lettering", "3D Lettering, Photo Walls &amp; Backdrops",
     "3D lettering, light-box backdrops and photo walls.",
     "Sculpted 3D lettering, illuminated light-box backdrops, stretch-fabric walls and photo spots designed for guests and press."),
    ("column-wraps", "Column Wraps, Wayfinding &amp; Décor",
     "Column wraps, LED cubes, wayfinding totems and themed décor across the venue.",
     "Column wraps, LED cubes, wayfinding totems, acrylic lecterns and themed décor that carry the brand through the venue."),
    ("stand-design", "Exhibition Stand Design",
     "Custom exhibition stand concepts.",
     "Exhibition stand concepts designed for trade-show participation."),
]

# Homepage cards: (category anchor, photo file). First card is the large one.
HOMEPAGE = [
    ("led-tunnels", "led-tunnel-entrance-vakifbank-management-summit-turkey"),
    ("stages", "led-wall-stage-light-show-corporate-event-turkey"),
    ("registration", "led-registration-desk-rixos-sungate-antalya"),
    ("branded-entrances", "building-facade-wrap-bellona-dealer-meeting-turkey"),
    ("3d-lettering", "3d-lettering-stage-backdrop-eksim-meeting-turkey"),
    ("conference", "plenary-conference-setup-cw-enerji-antalya"),
]

# (source upload, new name, category, alt text, caption). Dimensions are read from the files.
PHOTOS = [
    # LED tunnels & entrance arches
    ("led-tunel-1.jpeg", "led-tunnel-entrance-vakifbank-management-summit-turkey", "led-tunnels",
     "LED tunnel entrance with illuminated arches and a race-car display at the VakıfBank Management Summit at Titanic Deluxe Golf Belek, Antalya",
     "LED arch tunnel with race-car display — VakıfBank Management Summit"),
    ("led-tunel-2.jpeg", "illuminated-led-arch-entrance-vakifbank-summit-turkey", "led-tunnels",
     "Illuminated LED arch entrance in a hotel lobby for the VakıfBank Management Summit at Titanic Deluxe Golf Belek, Antalya",
     "Illuminated LED arch entrance — VakıfBank Management Summit"),
    ("isikli-tunel.png", "light-tunnel-hotel-entrance-vakifbank-summit-2025-turkey", "led-tunnels",
     "Radial light tunnel framing a hotel entrance for the VakıfBank Management Summit 2025 at Titanic Deluxe Golf Belek, Antalya",
     "Radial light tunnel at the hotel entrance — VakıfBank Management Summit 2025"),
    ("led-tunel-6.png", "led-screen-tunnel-entrance-cw-enerji-antalya", "led-tunnels",
     "LED screen tunnel entrance with pink and blue lighting for the CW Enerji dealer meeting in Antalya",
     "LED screen tunnel entrance — CW Enerji dealer meeting, Antalya"),
    ("led-tunel-3.jpeg", "branded-led-corridor-turk-telekom-event-turkey", "led-tunnels",
     "Blue branded corridor with wrapped columns and LED arches at the Türk Telekom Business Partners Meeting, Rixos Sungate, Antalya",
     "Branded corridor with wrapped columns and LED arches — Türk Telekom, Rixos Sungate"),
    ("led-tunel-4.jpeg", "led-arch-walkway-column-wraps-turk-telekom-turkey", "led-tunnels",
     "LED arch walkway with branded column wraps and display cubes at the Türk Telekom Business Partners Meeting, Rixos Sungate, Antalya",
     "LED arch walkway and column wraps — Türk Telekom, Rixos Sungate"),
    ("led-tunel-5.jpeg", "red-carpet-led-entrance-mapfre-sigorta-antalya", "led-tunnels",
     "Red-carpet entrance leading to an LED-framed doorway at the MAPFRE Sigorta event in Antalya",
     "Red-carpet LED entrance — MAPFRE Sigorta, Antalya"),
    # Stages, LED walls & show lighting
    ("ledwall-sahne-1.jpeg", "led-wall-stage-light-show-corporate-event-turkey", "stages",
     "Corporate event stage with full-width LED wall and moving-light beam show in a ballroom, Türkiye",
     "LED wall stage and moving-light show"),
    ("etkinlik-sahnesi-2.jpeg", "theatre-style-stage-led-screens-jti-meeting-turkey", "stages",
     "Theatre-style ballroom with LED screens and lighting rig for a JTI “Tek Ekip” meeting, Türkiye",
     "Theatre-style stage with LED screens — JTI “Tek Ekip” meeting"),
    ("ledwall-sahne-3.jpeg", "curved-led-wall-stage-viennalife-event-turkey", "stages",
     "Wide curved LED wall stage with lit stage steps for a Viennalife corporate event, Türkiye",
     "Curved LED wall stage — Viennalife corporate event"),
    ("acik-hava-sahnesi.jpeg", "open-air-ceremony-stage-istek-schools-antalya", "stages",
     "Open-air graduation ceremony stage with truss, LED screens and red-carpet aisle for İSTEK Schools in Antalya",
     "Open-air graduation stage — İSTEK Schools, Antalya"),
    ("orkestra-sahnesi.jpeg", "string-quartet-stage-backdrop-bellona-event-turkey", "stages",
     "String quartet performing in front of an illuminated “İyi ki Varsın Yanımda” backdrop at a Bellona event, Türkiye",
     "Live string quartet stage — Bellona dealer meeting"),
    # Conference & plenary
    ("toplanti-sahnesi-3.png", "plenary-conference-setup-cw-enerji-antalya", "conference",
     "Plenary conference room in classroom set-up under a blue lit ceiling with stage screens for the CW Enerji dealer meeting in Antalya",
     "Plenary set-up for the CW Enerji dealer and sales meeting, Antalya"),
    ("toplanti-sahnesi-2.jpeg", "classroom-conference-setup-led-screens-turkey", "conference",
     "Classroom-style conference set-up with truss stage, LED screens and camera crane in a hotel ballroom, Türkiye",
     "Classroom conference set-up with LED screens and camera crane"),
    ("toplanti-sahnesi-1.jpeg", "dealer-meeting-conference-stage-iveco-turkey", "conference",
     "Dealer meeting conference room with IVECO 50 years LED stage and table branding, Türkiye",
     "Dealer meeting stage and room branding — IVECO 50 years"),
    # Registration & welcome desks
    ("kayit-destek-2.jpeg", "led-registration-desk-rixos-sungate-antalya", "registration",
     "LED-fronted registration desk with lounge seating in the lobby of Rixos Sungate, Kemer, Antalya",
     "LED registration desk — Rixos Sungate, Antalya"),
    ("kayit-destek-6.png", "branded-registration-desk-cw-enerji-antalya", "registration",
     "Branded registration desk with staff for the CW Enerji 15th dealer and sales meeting at Nirvana Cosmopolitan, Antalya",
     "Registration desk — CW Enerji 15th dealer meeting, Nirvana Cosmopolitan, Antalya"),
    ("kayit-destek-4.jpeg", "welcome-desk-led-backdrop-iveco-50-years-turkey", "registration",
     "Welcome desk area with LED backdrop for the IVECO 50 years dealer meeting, Türkiye",
     "Welcome area with LED backdrop — IVECO 50 years"),
    ("kayit-destek-1.jpeg", "registration-counter-viennalife-event-turkey", "registration",
     "Branded registration counter with event staff for a Viennalife corporate event, Türkiye",
     "Registration counter and staff — Viennalife"),
    # Branded entrances & building wraps
    ("one-vision-kaplama.jpeg", "building-facade-wrap-bellona-dealer-meeting-turkey", "branded-entrances",
     "Hotel building façade fully wrapped in one-way vision graphics for the Bellona dealer meeting, Türkiye",
     "One-way vision façade wrap — Bellona dealer meeting"),
    ("custom-vinil-germe.jpeg", "gate-wrap-welcome-banner-anadolu-sigorta-kremlin-palace-antalya", "branded-entrances",
     "Custom stretched vinyl welcome wrap on the gate of Kremlin Palace for Anadolu Sigorta’s 100th anniversary, Antalya",
     "Gate welcome wrap — Anadolu Sigorta 100th anniversary, Kremlin Palace, Antalya"),
    ("giris-tag-1.png", "branded-hotel-entrance-vakifbank-summit-2025-turkey", "branded-entrances",
     "Branded hotel entrance arch with LED accents for the VakıfBank Management Summit 2025 at Titanic Deluxe Golf Belek, Antalya",
     "Branded hotel entrance — VakıfBank Management Summit 2025"),
    ("giris-tag-2.jpeg", "hotel-entrance-branding-vakifbank-summit-2024-turkey", "branded-entrances",
     "Hotel entrance dressed with campaign branding for the VakıfBank Management Summit 2024 at Titanic Deluxe Golf Belek, Antalya",
     "Hotel entrance branding — VakıfBank Management Summit 2024"),
    ("anlik-vinil-germe.jpeg", "canopy-banner-vakifbank-summit-2024-turkey", "branded-entrances",
     "Stretched vinyl banner on a hotel canopy for the VakıfBank Management Summit 2024 at Titanic Deluxe Golf Belek, Antalya",
     "Canopy banner — VakıfBank Management Summit 2024"),
    ("beach-flag-2.jpeg", "beach-flags-truck-display-iveco-event-turkey", "branded-entrances",
     "IVECO beach flags lining a truck display outside a hotel during a dealer event, Türkiye",
     "Beach flags and vehicle display — IVECO"),
    # 3D lettering, photo walls & backdrops
    ("strafor-dummy-2.jpeg", "3d-lettering-stage-backdrop-eksim-meeting-turkey", "3d-lettering",
     "Sculpted 3D foam lettering “Güç Sende Güç Sahada” in front of an LED backdrop at an Eksim meeting, Türkiye",
     "3D foam lettering on stage — Eksim meeting"),
    ("strafor-dummy-1.jpeg", "3d-clapperboard-sculpture-mapfre-sigorta-antalya", "3d-lettering",
     "Oversized 3D clapperboard sculpture with the “Başarınıza Sahne Sizin” campaign at the MAPFRE Sigorta event in Antalya",
     "3D clapperboard sculpture — MAPFRE Sigorta, Antalya"),
    ("isikli-folyo-kaplama.jpeg", "illuminated-lightbox-backdrop-bellona-turkey", "3d-lettering",
     "Illuminated light-box backdrop “İyi ki Varsın Yanımda” for the Bellona dealer meeting, Türkiye",
     "Illuminated light-box backdrop — Bellona"),
    ("vinil-germe-3.jpeg", "stretch-fabric-backdrop-jti-tek-ekip-turkey", "3d-lettering",
     "Twin stretch-fabric backdrops with “Tek Ekip Tek Yürek” graphics for a JTI meeting, Türkiye",
     "Stretch-fabric backdrops — JTI “Tek Ekip”"),
    ("vinil-germe-4.jpeg", "welcome-backdrop-mapfre-sigorta-antalya", "3d-lettering",
     "Outdoor welcome backdrop for the MAPFRE Sigorta agency meeting in Antalya",
     "Welcome backdrop — MAPFRE Sigorta agency meeting, Antalya"),
    ("fotograf-alani-2.jpeg", "photo-wall-step-and-repeat-istek-graduation-antalya", "3d-lettering",
     "Step-and-repeat photo wall on a raised platform for the İSTEK Schools graduation ceremony in Antalya",
     "Photo wall — İSTEK Schools graduation, Antalya"),
    ("led-ekranli-vinil-germe.jpeg", "led-screen-totem-vakifbank-summit-2024-turkey", "3d-lettering",
     "Stretched vinyl totem with built-in LED screen for the VakıfBank Management Summit 2024 at Titanic Deluxe Golf Belek, Antalya",
     "LED screen totem — VakıfBank Management Summit 2024"),
    # Column wraps, wayfinding & décor
    ("kolon-giydirme-3.jpeg", "column-wraps-christmas-decor-jti-event-turkey", "column-wraps",
     "Branded column wraps with Christmas tree and penguin décor in a hotel lobby for a JTI event, Türkiye",
     "Column wraps and seasonal décor — JTI"),
    ("ferforje-giydirme.jpeg", "lobby-branding-totems-jti-tek-ekip-turkey", "column-wraps",
     "Hotel lobby branded with overhead banners, totems and seasonal décor for a JTI “Tek Ekip” event, Türkiye",
     "Lobby branding and totems — JTI “Tek Ekip”"),
    ("kolon-giydirme-4.jpeg", "column-wraps-hotel-lobby-viennalife-turkey", "column-wraps",
     "Hotel lobby with Viennalife branded column wraps along the walkway, Türkiye",
     "Column wraps — Viennalife"),
    ("kolon-giydirme-1.png", "column-wrap-cw-enerji-antalya", "column-wraps",
     "Tall branded column wrap for the CW Enerji 15th dealer meeting in Antalya",
     "Column wrap — CW Enerji, Antalya"),
    ("kup-led.jpeg", "stacked-led-cubes-eksim-event-turkey", "column-wraps",
     "Stacked LED display cubes with Eksim branding in a hotel lobby, Türkiye",
     "Stacked LED cubes — Eksim"),
    ("kup-yonlendirme-1.png", "branded-cube-totem-cw-enerji-antalya", "column-wraps",
     "Stacked branded cube totem for the CW Enerji dealer meeting in Antalya",
     "Cube totem — CW Enerji, Antalya"),
    ("kup-yonlendirme-3.jpeg", "wayfinding-cube-totem-anadolu-sigorta-kremlin-palace-antalya", "column-wraps",
     "Wayfinding cube totem pointing to the main hall for Anadolu Sigorta’s 100th anniversary at Kremlin Palace, Antalya",
     "Wayfinding totem — Anadolu Sigorta 100th anniversary, Antalya"),
    ("pleksi-kursu.jpeg", "acrylic-lectern-istek-graduation-antalya", "column-wraps",
     "Clear acrylic lectern with İSTEK Antalya Schools branding at an open-air graduation ceremony",
     "Acrylic lectern — İSTEK Schools graduation, Antalya"),
    # Exhibition stand design
    ("stant-2.png", "exhibition-stand-design-ashib-3d-visual", "stand-design",
     "3D design visual of an exhibition stand for ASHİB with dairy product graphics and meeting table",
     "Exhibition stand design (3D visual) — ASHİB"),
]
